import { useMemo, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { Download, Share2, X } from 'lucide-react'
import Header from '../components/Header.jsx'
import Card from '../components/Card.jsx'
import { moods, moodMap } from '../utils/mood.js'
import { exportNode } from '../utils/share.js'

export default function DiaryPage({entries,onSave}){
  const [cursor,setCursor]=useState(new Date()); const [pick,setPick]=useState(null); const storyRef=useRef(null)
  const days=useMemo(()=>calendarDays(cursor),[cursor]); const ym=cursor.toLocaleDateString('zh-HK',{year:'numeric',month:'long'}); const entry=pick?entries[pick]:null
  return <div><Header title="情緒日記" subtitle="每一天，都會慢慢成為你的情緒地圖。" />
    <Card className="mb-4"><div className="flex justify-between items-center mb-4"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))} className="px-3 py-2 rounded-full bg-white/70">‹</button><h2 className="font-black text-xl">{ym}</h2><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))} className="px-3 py-2 rounded-full bg-white/70">›</button></div><div className="grid grid-cols-7 gap-2 text-center text-xs text-stone-500 mb-2">{'日一二三四五六'.split('').map(d=><span key={d}>{d}</span>)}</div><div className="grid grid-cols-7 gap-2">{days.map((d,i)=>{const e=d?entries[d]:null; const m=e?moodMap[e.mood]:null; return <motion.button whileTap={{scale:.9}} key={i} disabled={!d} onClick={()=>setPick(d)} className="aspect-square rounded-2xl text-xs font-bold flex flex-col items-center justify-center border border-white/60" style={{background:m?m.soft:'rgba(255,255,255,.45)'}}>{d&&<><span>{Number(d.slice(-2))}</span><span className="text-lg">{m?.emoji||'+'}</span></>}</motion.button>})}</div></Card>
    {pick&&<div className="fixed inset-0 z-[70] bg-black/30 p-4 flex items-end"><motion.div initial={{y:80,opacity:0}} animate={{y:0,opacity:1}} className="glass rounded-[2rem] p-5 w-full max-w-lg mx-auto shadow-soft"><div className="flex justify-between items-center"><h3 className="font-black text-xl">{pick}</h3><button onClick={()=>setPick(null)}><X/></button></div>{entry?<><div className="text-6xl my-4">{moodMap[entry.mood].emoji}</div><p className="font-black">{moodMap[entry.mood].zh}</p><p className="mt-3 text-stone-600 whitespace-pre-wrap">{entry.note||'沒有文字日記。'}</p><p className="text-xs text-stone-500 mt-3">建立時間：{new Date(entry.createdAt).toLocaleString('zh-HK')}</p></>:<p className="my-5 text-stone-500">這天未有記錄。你可以在記錄頁新增今天記錄；若要補記，可先在下方快速建立。</p>}<QuickAdd date={pick} entry={entry} onSave={onSave}/><div className="mt-4 flex gap-2"><button onClick={()=>exportNode(storyRef.current,`joyage-${pick}.png`)} className="flex-1 rounded-2xl bg-stone-900 text-white py-3 font-bold flex items-center justify-center gap-2"><Share2 size={18}/>分享卡</button><button onClick={()=>exportNode(storyRef.current,`joyage-${pick}.png`)} className="rounded-2xl bg-white/70 px-4"><Download size={18}/></button></div><div className="fixed -left-[9999px]"><Story refEl={storyRef} date={pick} entry={entry}/></div></motion.div></div>}
  </div>
}
function QuickAdd({date,entry,onSave}){const [mood,setMood]=useState(entry?.mood||'joy'); const [note,setNote]=useState(entry?.note||''); return <div className="mt-4"><div className="flex gap-2 overflow-x-auto no-scrollbar">{moods.map(m=><button key={m.key} onClick={()=>setMood(m.key)} className="rounded-full px-3 py-2 bg-white/70 text-xl border" style={{borderColor:mood===m.key?'#111':'transparent'}}>{m.emoji}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-3 w-full rounded-2xl bg-white/70 p-3" rows={3} placeholder="補寫這一天..."/><button onClick={()=>onSave({date,mood,note,createdAt:entry?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),timeBucket:'補記'})} className="mt-2 w-full rounded-2xl bg-white/80 py-3 font-black">儲存這一天</button></div>}
function Story({refEl,date,entry}){const m=entry?moodMap[entry.mood]:moodMap.joy; return <div ref={refEl} className={`story-card bg-gradient-to-br ${m.gradient} p-8 flex flex-col justify-between`}><div><p className="font-black text-2xl">Joyage Daily</p><p className="text-stone-500">把每天的情緒，好好記下來。</p></div><div className="text-center"><div className="text-9xl mb-5">{m.emoji}</div><h2 className="text-5xl font-black">{m.zh}</h2><p className="mt-5 text-2xl leading-relaxed">{entry?.note||'今天，我有好好照顧自己。'}</p></div><p className="font-bold text-xl">{date}</p></div>}
function calendarDays(d){const y=d.getFullYear(),m=d.getMonth(); const first=new Date(y,m,1).getDay(); const total=new Date(y,m+1,0).getDate(); const arr=Array(first).fill(null); for(let day=1;day<=total;day++) arr.push(`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`); while(arr.length%7)arr.push(null); return arr}
